MotoActions: add LOCAL_OPTIONAL_USES_LIBRARIES
error: mismatch in the <uses-library> tags between the build system and the manifest:
        - required libraries in build system: []
                         vs. in the manifest: []
        - optional libraries in build system: []
                         vs. in the manifest: [androidx.window.extensions, androidx.window.sidecar]
        - tags in the manifest (/home/dark/drk/out/target/common/obj/APPS/PocketMode_intermediates/manifest/AndroidManifest.xml):
                <uses-library android:name=androidx.window.extensions android:required=false/>
                <uses-library android:name=androidx.window.sidecar android:required=false/>